name: Update GitHub Activity
on: workflow_dispatch # Allows manual triggering
jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Github Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "juhasauna"
          GITHUB_TOKEN: ${{ secrets.NTUST-devops-assignment3 }}
